Revert "thread: Judge joinable before join"
To fix:
thread.cpp: In destructor ‘virtual Thread::~Thread()’:
thread.cpp:71:19: error: ‘class NativeThread’ has no member named ‘joinable’
   71 |     if (stdThread.joinable()) {
      |                   ^~~~~~~~
make: *** [<builtin>: thread.o] Error 1

This reverts commit 2dfee5c67092502983f444f8073ecd856d386a9d.

Change-Id: I528404357c26d1781c3b2d9673ea6f60be38a995